name: Build and Test

on: [ push ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false


    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.12'
    - name: Install poetry and pipx
      run: |
        pip install poetry && pip install pipx

    - name: Install global dependencies
      run: |
        pipx install isort && pipx install black && pipx install bandit && \
        pipx install pylint && pipx install poetry

    - name: Install Dependencies
      run: poetry install --with dev

    - name: Run Makefile
      run: make check
